baseURL = 'https://gelerion.github.io/'
languageCode = 'en-us'
title = 'Gelerion Blog'
author = "Denis"
theme = 'beautifulhugo'

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Shown in the side menu
copyright = "&copy; 2023. All rights reserved."
canonifyurls = true
paginate = 10
googleAnalytics = "G-962FFPME5F"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  subtitle = ""
  brand = "Gelerion"
  disqus = "Gelerion"
  dateFormat = "02 Jan 2006, 15:04"

  comments = true
  readingTime = true
  wordCount = true
  #useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
 
[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  #name = "Gelerion"
  website = "yourwebsite.com"
  #email = "youremail@domain.com"
  github = "Gelerion"
  linkedin = "denisshuvalov"
  stackoverflow = "users/6350670/gelerion"

# https://gohugo.io/content-management/taxonomies/
[taxonomies]
  tag = 'tags'
  category = 'categories'


[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Tags"
    weight = 4
    identifier = "tags"
    url = "/tags/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'github'
    tabWidth = 4

#demo: https://hugo-theme-beautifulhugo.netlify.app/