baseURL = 'https://gelerion.github.io/'
languageCode = 'en-us'
title = 'Gelerion Blog'
author = "Denis Shuvalov"
theme = 'beautifulhugo'
description  = "Java, JVM performance, Streaming & AI engineering notes"
keywords = [
  "java",
  "jvm",
  "spring-boot",
  "microservices",
  "streaming",
  "lakehouse",
  "flink",
  "kafka",
  "trino",
  "performance",
  "ai",
  "rag",
  "openai",
  "vector-databases",
  "api-design",
  "architecture",
  "observability",
  "terraform",
  "kubernetes",
  "design-docs"
]

enableRobotsTXT = true 
enableGitInfo = true
summaryLength = 70

# Shown in the side menu
copyright = "&copy; Denis Shuvalov. All rights reserved."
canonifyurls = true
googleAnalytics = "G-962FFPME5F"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  subtitle = ""
  brand = "Gelerion"
  disqus = "Gelerion"
  dateFormat = "02 Jan 2006"
  favicon = "favicon.ico"
  
  comments = true
  readingTime = true
  wordCount = true
  #useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[params.plausible]
  domain = "gelerion.github.io"

[related]
  threshold = 80 # Lower score means more matches (default 80)
  includeNewer = true
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100 
  [[related.indices]]
    name = "categories"
    weight = 80
  [[related.indices]]
    name = "series"
    weight = 120 

[pagination]
  pagerSize = 10
 
[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  #name = "Gelerion"
  website = "https://gelerion.github.io/"
  #email = "youremail@domain.com"
  github = "Gelerion"
  linkedin = "denisshuvalov"
  stackoverflow = "users/6350670/gelerion"

# https://gohugo.io/content-management/taxonomies/
[taxonomies]
  tag = 'tags'
  category = 'categories'
  series = "series"


[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    weight = 2
    identifier = "posts"
    url = "/posts/"
  [[menu.main]]
    name = "Tags"
    weight = 4
    identifier = "tags"
    url = "/tags/"
  [[menu.main]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/about/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'github'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered = false

[services]
  [services.disqus]
    shortname = "Gelerion"

[outputs]
  home    = ["HTML", "RSS", "JSON"]   # RSS for readers, JSON for search
  section = ["HTML", "RSS"]

# Optional lightweight search for a static site
[outputFormats.JSON]
  mediaType = "application/json"
  baseName  = "index"

[minify]
  disableXML = true         

[asset]                     
  [asset.postCSS]
    includeFiles = ["css/**/*.css"]

[development]
  buildDrafts = true
  buildFuture = true

#demo: https://hugo-theme-beautifulhugo.netlify.app/